import type HapticDeviceCapability from './haptic_device_capability_type';
import type HapticEventEventType from './haptic_event_event_type_type';
import type HapticEventParameterID from './haptic_event_parameter_id_type';
import type HapticEventParameter from './haptic_event_parameter_type';
import type HapticEvent from './haptic_event_type';
import type HapticPattern from './haptic_pattern_type';
import HapticEngine from './haptic_engine_type';
export { HapticEngine };
export declare type HapticDeviceCapabilityType = HapticDeviceCapability;
export declare type HapticEventEventTypeType = HapticEventEventType;
export declare type HapticEventParameterIDType = HapticEventParameterID;
export declare type HapticEventParameterType = HapticEventParameter;
export declare type HapticEventType = HapticEvent;
export declare type HapticPatternType = HapticPattern;
